#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mock.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EPcloth")]
	public partial class modelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUserSession(UserSession instance);
    partial void UpdateUserSession(UserSession instance);
    partial void DeleteUserSession(UserSession instance);
    partial void InsertClothDetail(ClothDetail instance);
    partial void UpdateClothDetail(ClothDetail instance);
    partial void DeleteClothDetail(ClothDetail instance);
    partial void InsertDicEntry(DicEntry instance);
    partial void UpdateDicEntry(DicEntry instance);
    partial void DeleteDicEntry(DicEntry instance);
    partial void InsertDictionary(Dictionary instance);
    partial void UpdateDictionary(Dictionary instance);
    partial void DeleteDictionary(Dictionary instance);
    partial void InsertDownCloth(DownCloth instance);
    partial void UpdateDownCloth(DownCloth instance);
    partial void DeleteDownCloth(DownCloth instance);
    partial void InsertOperClothLog(OperClothLog instance);
    partial void UpdateOperClothLog(OperClothLog instance);
    partial void DeleteOperClothLog(OperClothLog instance);
    partial void InsertUpCloth(UpCloth instance);
    partial void UpdateUpCloth(UpCloth instance);
    partial void DeleteUpCloth(UpCloth instance);
    #endregion
		
		public modelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EPclothConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UserSession> UserSessions
		{
			get
			{
				return this.GetTable<UserSession>();
			}
		}
		
		public System.Data.Linq.Table<ClothDetail> ClothDetails
		{
			get
			{
				return this.GetTable<ClothDetail>();
			}
		}
		
		public System.Data.Linq.Table<DicEntry> DicEntries
		{
			get
			{
				return this.GetTable<DicEntry>();
			}
		}
		
		public System.Data.Linq.Table<Dictionary> Dictionaries
		{
			get
			{
				return this.GetTable<Dictionary>();
			}
		}
		
		public System.Data.Linq.Table<DownCloth> DownCloths
		{
			get
			{
				return this.GetTable<DownCloth>();
			}
		}
		
		public System.Data.Linq.Table<OperClothLog> OperClothLogs
		{
			get
			{
				return this.GetTable<OperClothLog>();
			}
		}
		
		public System.Data.Linq.Table<UpCloth> UpCloths
		{
			get
			{
				return this.GetTable<UpCloth>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _PassWord;
		
		private string _RealName;
		
		private string _UserType;
		
		private string _UserFunSet;
		
		private System.DateTime _CreateDT;
		
		private System.DateTime _ModifiedDT;
		
		private bool _IsDeleted;
		
		private EntitySet<UserSession> _UserSessions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnUserFunSetChanging(string value);
    partial void OnUserFunSetChanged();
    partial void OnCreateDTChanging(System.DateTime value);
    partial void OnCreateDTChanged();
    partial void OnModifiedDTChanging(System.DateTime value);
    partial void OnModifiedDTChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public User()
		{
			this._UserSessions = new EntitySet<UserSession>(new Action<UserSession>(this.attach_UserSessions), new Action<UserSession>(this.detach_UserSessions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFunSet", DbType="NVarChar(50)")]
		public string UserFunSet
		{
			get
			{
				return this._UserFunSet;
			}
			set
			{
				if ((this._UserFunSet != value))
				{
					this.OnUserFunSetChanging(value);
					this.SendPropertyChanging();
					this._UserFunSet = value;
					this.SendPropertyChanged("UserFunSet");
					this.OnUserFunSetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDT", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDT
		{
			get
			{
				return this._ModifiedDT;
			}
			set
			{
				if ((this._ModifiedDT != value))
				{
					this.OnModifiedDTChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDT = value;
					this.SendPropertyChanged("ModifiedDT");
					this.OnModifiedDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserSession", Storage="_UserSessions", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<UserSession> UserSessions
		{
			get
			{
				return this._UserSessions;
			}
			set
			{
				this._UserSessions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserSessions(UserSession entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_UserSessions(UserSession entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserSession")]
	public partial class UserSession : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private int _UserId;
		
		private System.DateTime _LoginDT;
		
		private System.DateTime _LastActivityDT;
		
		private string _RemoteIP;
		
		private string _Status;
		
		private System.DateTime _CreateDT;
		
		private System.DateTime _ModifiedDT;
		
		private bool _IsDeleted;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnLoginDTChanging(System.DateTime value);
    partial void OnLoginDTChanged();
    partial void OnLastActivityDTChanging(System.DateTime value);
    partial void OnLastActivityDTChanged();
    partial void OnRemoteIPChanging(string value);
    partial void OnRemoteIPChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateDTChanging(System.DateTime value);
    partial void OnCreateDTChanged();
    partial void OnModifiedDTChanging(System.DateTime value);
    partial void OnModifiedDTChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public UserSession()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginDT", DbType="DateTime NOT NULL")]
		public System.DateTime LoginDT
		{
			get
			{
				return this._LoginDT;
			}
			set
			{
				if ((this._LoginDT != value))
				{
					this.OnLoginDTChanging(value);
					this.SendPropertyChanging();
					this._LoginDT = value;
					this.SendPropertyChanged("LoginDT");
					this.OnLoginDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDT", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivityDT
		{
			get
			{
				return this._LastActivityDT;
			}
			set
			{
				if ((this._LastActivityDT != value))
				{
					this.OnLastActivityDTChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDT = value;
					this.SendPropertyChanged("LastActivityDT");
					this.OnLastActivityDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemoteIP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RemoteIP
		{
			get
			{
				return this._RemoteIP;
			}
			set
			{
				if ((this._RemoteIP != value))
				{
					this.OnRemoteIPChanging(value);
					this.SendPropertyChanging();
					this._RemoteIP = value;
					this.SendPropertyChanged("RemoteIP");
					this.OnRemoteIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDT", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDT
		{
			get
			{
				return this._ModifiedDT;
			}
			set
			{
				if ((this._ModifiedDT != value))
				{
					this.OnModifiedDTChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDT = value;
					this.SendPropertyChanged("ModifiedDT");
					this.OnModifiedDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserSession", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserSessions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserSessions.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClothDetail")]
	public partial class ClothDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SYTLE_NO;
		
		private string _BIG_NO;
		
		private string _CHICUN_SHUXING;
		
		private string _CHICHU_DAXIAO;
		
		private string _OTHER;
		
		private string _ADD_ENABLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSYTLE_NOChanging(int value);
    partial void OnSYTLE_NOChanged();
    partial void OnBIG_NOChanging(string value);
    partial void OnBIG_NOChanged();
    partial void OnCHICUN_SHUXINGChanging(string value);
    partial void OnCHICUN_SHUXINGChanged();
    partial void OnCHICHU_DAXIAOChanging(string value);
    partial void OnCHICHU_DAXIAOChanged();
    partial void OnOTHERChanging(string value);
    partial void OnOTHERChanged();
    partial void OnADD_ENABLEChanging(string value);
    partial void OnADD_ENABLEChanged();
    #endregion
		
		public ClothDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYTLE_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYTLE_NO
		{
			get
			{
				return this._SYTLE_NO;
			}
			set
			{
				if ((this._SYTLE_NO != value))
				{
					this.OnSYTLE_NOChanging(value);
					this.SendPropertyChanging();
					this._SYTLE_NO = value;
					this.SendPropertyChanged("SYTLE_NO");
					this.OnSYTLE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIG_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BIG_NO
		{
			get
			{
				return this._BIG_NO;
			}
			set
			{
				if ((this._BIG_NO != value))
				{
					this.OnBIG_NOChanging(value);
					this.SendPropertyChanging();
					this._BIG_NO = value;
					this.SendPropertyChanged("BIG_NO");
					this.OnBIG_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHICUN_SHUXING", DbType="NVarChar(50)")]
		public string CHICUN_SHUXING
		{
			get
			{
				return this._CHICUN_SHUXING;
			}
			set
			{
				if ((this._CHICUN_SHUXING != value))
				{
					this.OnCHICUN_SHUXINGChanging(value);
					this.SendPropertyChanging();
					this._CHICUN_SHUXING = value;
					this.SendPropertyChanged("CHICUN_SHUXING");
					this.OnCHICUN_SHUXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHICHU_DAXIAO", DbType="NVarChar(50)")]
		public string CHICHU_DAXIAO
		{
			get
			{
				return this._CHICHU_DAXIAO;
			}
			set
			{
				if ((this._CHICHU_DAXIAO != value))
				{
					this.OnCHICHU_DAXIAOChanging(value);
					this.SendPropertyChanging();
					this._CHICHU_DAXIAO = value;
					this.SendPropertyChanged("CHICHU_DAXIAO");
					this.OnCHICHU_DAXIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHER", DbType="NVarChar(50)")]
		public string OTHER
		{
			get
			{
				return this._OTHER;
			}
			set
			{
				if ((this._OTHER != value))
				{
					this.OnOTHERChanging(value);
					this.SendPropertyChanging();
					this._OTHER = value;
					this.SendPropertyChanged("OTHER");
					this.OnOTHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_ENABLE", DbType="NVarChar(50)")]
		public string ADD_ENABLE
		{
			get
			{
				return this._ADD_ENABLE;
			}
			set
			{
				if ((this._ADD_ENABLE != value))
				{
					this.OnADD_ENABLEChanging(value);
					this.SendPropertyChanging();
					this._ADD_ENABLE = value;
					this.SendPropertyChanged("ADD_ENABLE");
					this.OnADD_ENABLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DicEntry")]
	public partial class DicEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ENTRY_CODE;
		
		private string _ENTRY_NAME;
		
		private string _VALUE_RANGE;
		
		private string _SUB_LENGTH;
		
		private string _ENTRY_STATUS;
		
		private string _ADD_ENABLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENTRY_CODEChanging(int value);
    partial void OnENTRY_CODEChanged();
    partial void OnENTRY_NAMEChanging(string value);
    partial void OnENTRY_NAMEChanged();
    partial void OnVALUE_RANGEChanging(string value);
    partial void OnVALUE_RANGEChanged();
    partial void OnSUB_LENGTHChanging(string value);
    partial void OnSUB_LENGTHChanged();
    partial void OnENTRY_STATUSChanging(string value);
    partial void OnENTRY_STATUSChanged();
    partial void OnADD_ENABLEChanging(string value);
    partial void OnADD_ENABLEChanged();
    #endregion
		
		public DicEntry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_CODE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ENTRY_CODE
		{
			get
			{
				return this._ENTRY_CODE;
			}
			set
			{
				if ((this._ENTRY_CODE != value))
				{
					this.OnENTRY_CODEChanging(value);
					this.SendPropertyChanging();
					this._ENTRY_CODE = value;
					this.SendPropertyChanged("ENTRY_CODE");
					this.OnENTRY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_NAME", DbType="NVarChar(50)")]
		public string ENTRY_NAME
		{
			get
			{
				return this._ENTRY_NAME;
			}
			set
			{
				if ((this._ENTRY_NAME != value))
				{
					this.OnENTRY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ENTRY_NAME = value;
					this.SendPropertyChanged("ENTRY_NAME");
					this.OnENTRY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE_RANGE", DbType="NVarChar(50)")]
		public string VALUE_RANGE
		{
			get
			{
				return this._VALUE_RANGE;
			}
			set
			{
				if ((this._VALUE_RANGE != value))
				{
					this.OnVALUE_RANGEChanging(value);
					this.SendPropertyChanging();
					this._VALUE_RANGE = value;
					this.SendPropertyChanged("VALUE_RANGE");
					this.OnVALUE_RANGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_LENGTH", DbType="NVarChar(50)")]
		public string SUB_LENGTH
		{
			get
			{
				return this._SUB_LENGTH;
			}
			set
			{
				if ((this._SUB_LENGTH != value))
				{
					this.OnSUB_LENGTHChanging(value);
					this.SendPropertyChanging();
					this._SUB_LENGTH = value;
					this.SendPropertyChanged("SUB_LENGTH");
					this.OnSUB_LENGTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_STATUS", DbType="NVarChar(50)")]
		public string ENTRY_STATUS
		{
			get
			{
				return this._ENTRY_STATUS;
			}
			set
			{
				if ((this._ENTRY_STATUS != value))
				{
					this.OnENTRY_STATUSChanging(value);
					this.SendPropertyChanging();
					this._ENTRY_STATUS = value;
					this.SendPropertyChanged("ENTRY_STATUS");
					this.OnENTRY_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_ENABLE", DbType="NVarChar(50)")]
		public string ADD_ENABLE
		{
			get
			{
				return this._ADD_ENABLE;
			}
			set
			{
				if ((this._ADD_ENABLE != value))
				{
					this.OnADD_ENABLEChanging(value);
					this.SendPropertyChanging();
					this._ADD_ENABLE = value;
					this.SendPropertyChanged("ADD_ENABLE");
					this.OnADD_ENABLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dictionary")]
	public partial class Dictionary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ENTRY_CODE;
		
		private int _SUB_CODE;
		
		private string _SUB_DESCRIBE;
		
		private string _SUB_STATUS;
		
		private System.Nullable<int> _SUB_ORDER;
		
		private string _USE_FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENTRY_CODEChanging(int value);
    partial void OnENTRY_CODEChanged();
    partial void OnSUB_CODEChanging(int value);
    partial void OnSUB_CODEChanged();
    partial void OnSUB_DESCRIBEChanging(string value);
    partial void OnSUB_DESCRIBEChanged();
    partial void OnSUB_STATUSChanging(string value);
    partial void OnSUB_STATUSChanged();
    partial void OnSUB_ORDERChanging(System.Nullable<int> value);
    partial void OnSUB_ORDERChanged();
    partial void OnUSE_FLAGChanging(string value);
    partial void OnUSE_FLAGChanged();
    #endregion
		
		public Dictionary()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_CODE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ENTRY_CODE
		{
			get
			{
				return this._ENTRY_CODE;
			}
			set
			{
				if ((this._ENTRY_CODE != value))
				{
					this.OnENTRY_CODEChanging(value);
					this.SendPropertyChanging();
					this._ENTRY_CODE = value;
					this.SendPropertyChanged("ENTRY_CODE");
					this.OnENTRY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CODE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SUB_CODE
		{
			get
			{
				return this._SUB_CODE;
			}
			set
			{
				if ((this._SUB_CODE != value))
				{
					this.OnSUB_CODEChanging(value);
					this.SendPropertyChanging();
					this._SUB_CODE = value;
					this.SendPropertyChanged("SUB_CODE");
					this.OnSUB_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_DESCRIBE", DbType="NVarChar(50)")]
		public string SUB_DESCRIBE
		{
			get
			{
				return this._SUB_DESCRIBE;
			}
			set
			{
				if ((this._SUB_DESCRIBE != value))
				{
					this.OnSUB_DESCRIBEChanging(value);
					this.SendPropertyChanging();
					this._SUB_DESCRIBE = value;
					this.SendPropertyChanged("SUB_DESCRIBE");
					this.OnSUB_DESCRIBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_STATUS", DbType="NVarChar(50)")]
		public string SUB_STATUS
		{
			get
			{
				return this._SUB_STATUS;
			}
			set
			{
				if ((this._SUB_STATUS != value))
				{
					this.OnSUB_STATUSChanging(value);
					this.SendPropertyChanging();
					this._SUB_STATUS = value;
					this.SendPropertyChanged("SUB_STATUS");
					this.OnSUB_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_ORDER", DbType="Int")]
		public System.Nullable<int> SUB_ORDER
		{
			get
			{
				return this._SUB_ORDER;
			}
			set
			{
				if ((this._SUB_ORDER != value))
				{
					this.OnSUB_ORDERChanging(value);
					this.SendPropertyChanging();
					this._SUB_ORDER = value;
					this.SendPropertyChanged("SUB_ORDER");
					this.OnSUB_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_FLAG", DbType="NVarChar(50)")]
		public string USE_FLAG
		{
			get
			{
				return this._USE_FLAG;
			}
			set
			{
				if ((this._USE_FLAG != value))
				{
					this.OnUSE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._USE_FLAG = value;
					this.SendPropertyChanged("USE_FLAG");
					this.OnUSE_FLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DownCloth")]
	public partial class DownCloth : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SYTLE_NO;
		
		private int _BIG_NO;
		
		private string _STYLE;
		
		private string _C_CLASS;
		
		private string _KUOXING;
		
		private string _KUANSONGFENGGE;
		
		private string _QUNCHANG;
		
		private string _YISHENZAOXING;
		
		private string _YAOGAO;
		
		private string _GONGYI;
		
		private string _COMMENTS;
		
		private string _YANGYI_LOCATION;
		
		private string _YANGYI_INFO;
		
		private string _KUANSHI_LOCATION;
		
		private string _KUANSHI_INFO;
		
		private string _BANXING_LOCAITON;
		
		private string _BANXING_INFO;
		
		private string _GONGYIWENJIAN;
		
		private string _GONGYIWENJIAN_INFO;
		
		private string _FULIAOKA;
		
		private string _FULIAOKA_INFO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSYTLE_NOChanging(int value);
    partial void OnSYTLE_NOChanged();
    partial void OnBIG_NOChanging(int value);
    partial void OnBIG_NOChanged();
    partial void OnSTYLEChanging(string value);
    partial void OnSTYLEChanged();
    partial void OnC_CLASSChanging(string value);
    partial void OnC_CLASSChanged();
    partial void OnKUOXINGChanging(string value);
    partial void OnKUOXINGChanged();
    partial void OnKUANSONGFENGGEChanging(string value);
    partial void OnKUANSONGFENGGEChanged();
    partial void OnQUNCHANGChanging(string value);
    partial void OnQUNCHANGChanged();
    partial void OnYISHENZAOXINGChanging(string value);
    partial void OnYISHENZAOXINGChanged();
    partial void OnYAOGAOChanging(string value);
    partial void OnYAOGAOChanged();
    partial void OnGONGYIChanging(string value);
    partial void OnGONGYIChanged();
    partial void OnCOMMENTSChanging(string value);
    partial void OnCOMMENTSChanged();
    partial void OnYANGYI_LOCATIONChanging(string value);
    partial void OnYANGYI_LOCATIONChanged();
    partial void OnYANGYI_INFOChanging(string value);
    partial void OnYANGYI_INFOChanged();
    partial void OnKUANSHI_LOCATIONChanging(string value);
    partial void OnKUANSHI_LOCATIONChanged();
    partial void OnKUANSHI_INFOChanging(string value);
    partial void OnKUANSHI_INFOChanged();
    partial void OnBANXING_LOCAITONChanging(string value);
    partial void OnBANXING_LOCAITONChanged();
    partial void OnBANXING_INFOChanging(string value);
    partial void OnBANXING_INFOChanged();
    partial void OnGONGYIWENJIANChanging(string value);
    partial void OnGONGYIWENJIANChanged();
    partial void OnGONGYIWENJIAN_INFOChanging(string value);
    partial void OnGONGYIWENJIAN_INFOChanged();
    partial void OnFULIAOKAChanging(string value);
    partial void OnFULIAOKAChanged();
    partial void OnFULIAOKA_INFOChanging(string value);
    partial void OnFULIAOKA_INFOChanged();
    #endregion
		
		public DownCloth()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYTLE_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYTLE_NO
		{
			get
			{
				return this._SYTLE_NO;
			}
			set
			{
				if ((this._SYTLE_NO != value))
				{
					this.OnSYTLE_NOChanging(value);
					this.SendPropertyChanging();
					this._SYTLE_NO = value;
					this.SendPropertyChanged("SYTLE_NO");
					this.OnSYTLE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIG_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BIG_NO
		{
			get
			{
				return this._BIG_NO;
			}
			set
			{
				if ((this._BIG_NO != value))
				{
					this.OnBIG_NOChanging(value);
					this.SendPropertyChanging();
					this._BIG_NO = value;
					this.SendPropertyChanged("BIG_NO");
					this.OnBIG_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STYLE", DbType="NVarChar(50)")]
		public string STYLE
		{
			get
			{
				return this._STYLE;
			}
			set
			{
				if ((this._STYLE != value))
				{
					this.OnSTYLEChanging(value);
					this.SendPropertyChanging();
					this._STYLE = value;
					this.SendPropertyChanged("STYLE");
					this.OnSTYLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CLASS", DbType="NVarChar(50)")]
		public string C_CLASS
		{
			get
			{
				return this._C_CLASS;
			}
			set
			{
				if ((this._C_CLASS != value))
				{
					this.OnC_CLASSChanging(value);
					this.SendPropertyChanging();
					this._C_CLASS = value;
					this.SendPropertyChanged("C_CLASS");
					this.OnC_CLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUOXING", DbType="NVarChar(50)")]
		public string KUOXING
		{
			get
			{
				return this._KUOXING;
			}
			set
			{
				if ((this._KUOXING != value))
				{
					this.OnKUOXINGChanging(value);
					this.SendPropertyChanging();
					this._KUOXING = value;
					this.SendPropertyChanged("KUOXING");
					this.OnKUOXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUANSONGFENGGE", DbType="NVarChar(50)")]
		public string KUANSONGFENGGE
		{
			get
			{
				return this._KUANSONGFENGGE;
			}
			set
			{
				if ((this._KUANSONGFENGGE != value))
				{
					this.OnKUANSONGFENGGEChanging(value);
					this.SendPropertyChanging();
					this._KUANSONGFENGGE = value;
					this.SendPropertyChanged("KUANSONGFENGGE");
					this.OnKUANSONGFENGGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUNCHANG", DbType="NVarChar(50)")]
		public string QUNCHANG
		{
			get
			{
				return this._QUNCHANG;
			}
			set
			{
				if ((this._QUNCHANG != value))
				{
					this.OnQUNCHANGChanging(value);
					this.SendPropertyChanging();
					this._QUNCHANG = value;
					this.SendPropertyChanged("QUNCHANG");
					this.OnQUNCHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YISHENZAOXING", DbType="NVarChar(50)")]
		public string YISHENZAOXING
		{
			get
			{
				return this._YISHENZAOXING;
			}
			set
			{
				if ((this._YISHENZAOXING != value))
				{
					this.OnYISHENZAOXINGChanging(value);
					this.SendPropertyChanging();
					this._YISHENZAOXING = value;
					this.SendPropertyChanged("YISHENZAOXING");
					this.OnYISHENZAOXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YAOGAO", DbType="NVarChar(50)")]
		public string YAOGAO
		{
			get
			{
				return this._YAOGAO;
			}
			set
			{
				if ((this._YAOGAO != value))
				{
					this.OnYAOGAOChanging(value);
					this.SendPropertyChanging();
					this._YAOGAO = value;
					this.SendPropertyChanged("YAOGAO");
					this.OnYAOGAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGYI", DbType="NVarChar(50)")]
		public string GONGYI
		{
			get
			{
				return this._GONGYI;
			}
			set
			{
				if ((this._GONGYI != value))
				{
					this.OnGONGYIChanging(value);
					this.SendPropertyChanging();
					this._GONGYI = value;
					this.SendPropertyChanged("GONGYI");
					this.OnGONGYIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(50)")]
		public string COMMENTS
		{
			get
			{
				return this._COMMENTS;
			}
			set
			{
				if ((this._COMMENTS != value))
				{
					this.OnCOMMENTSChanging(value);
					this.SendPropertyChanging();
					this._COMMENTS = value;
					this.SendPropertyChanged("COMMENTS");
					this.OnCOMMENTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YANGYI_LOCATION", DbType="NVarChar(100)")]
		public string YANGYI_LOCATION
		{
			get
			{
				return this._YANGYI_LOCATION;
			}
			set
			{
				if ((this._YANGYI_LOCATION != value))
				{
					this.OnYANGYI_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._YANGYI_LOCATION = value;
					this.SendPropertyChanged("YANGYI_LOCATION");
					this.OnYANGYI_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YANGYI_INFO", DbType="NVarChar(100)")]
		public string YANGYI_INFO
		{
			get
			{
				return this._YANGYI_INFO;
			}
			set
			{
				if ((this._YANGYI_INFO != value))
				{
					this.OnYANGYI_INFOChanging(value);
					this.SendPropertyChanging();
					this._YANGYI_INFO = value;
					this.SendPropertyChanged("YANGYI_INFO");
					this.OnYANGYI_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUANSHI_LOCATION", DbType="NVarChar(100)")]
		public string KUANSHI_LOCATION
		{
			get
			{
				return this._KUANSHI_LOCATION;
			}
			set
			{
				if ((this._KUANSHI_LOCATION != value))
				{
					this.OnKUANSHI_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._KUANSHI_LOCATION = value;
					this.SendPropertyChanged("KUANSHI_LOCATION");
					this.OnKUANSHI_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUANSHI_INFO", DbType="NVarChar(100)")]
		public string KUANSHI_INFO
		{
			get
			{
				return this._KUANSHI_INFO;
			}
			set
			{
				if ((this._KUANSHI_INFO != value))
				{
					this.OnKUANSHI_INFOChanging(value);
					this.SendPropertyChanging();
					this._KUANSHI_INFO = value;
					this.SendPropertyChanged("KUANSHI_INFO");
					this.OnKUANSHI_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANXING_LOCAITON", DbType="NVarChar(100)")]
		public string BANXING_LOCAITON
		{
			get
			{
				return this._BANXING_LOCAITON;
			}
			set
			{
				if ((this._BANXING_LOCAITON != value))
				{
					this.OnBANXING_LOCAITONChanging(value);
					this.SendPropertyChanging();
					this._BANXING_LOCAITON = value;
					this.SendPropertyChanged("BANXING_LOCAITON");
					this.OnBANXING_LOCAITONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANXING_INFO", DbType="NVarChar(100)")]
		public string BANXING_INFO
		{
			get
			{
				return this._BANXING_INFO;
			}
			set
			{
				if ((this._BANXING_INFO != value))
				{
					this.OnBANXING_INFOChanging(value);
					this.SendPropertyChanging();
					this._BANXING_INFO = value;
					this.SendPropertyChanged("BANXING_INFO");
					this.OnBANXING_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGYIWENJIAN", DbType="NVarChar(100)")]
		public string GONGYIWENJIAN
		{
			get
			{
				return this._GONGYIWENJIAN;
			}
			set
			{
				if ((this._GONGYIWENJIAN != value))
				{
					this.OnGONGYIWENJIANChanging(value);
					this.SendPropertyChanging();
					this._GONGYIWENJIAN = value;
					this.SendPropertyChanged("GONGYIWENJIAN");
					this.OnGONGYIWENJIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGYIWENJIAN_INFO", DbType="NVarChar(500)")]
		public string GONGYIWENJIAN_INFO
		{
			get
			{
				return this._GONGYIWENJIAN_INFO;
			}
			set
			{
				if ((this._GONGYIWENJIAN_INFO != value))
				{
					this.OnGONGYIWENJIAN_INFOChanging(value);
					this.SendPropertyChanging();
					this._GONGYIWENJIAN_INFO = value;
					this.SendPropertyChanged("GONGYIWENJIAN_INFO");
					this.OnGONGYIWENJIAN_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULIAOKA", DbType="NVarChar(100)")]
		public string FULIAOKA
		{
			get
			{
				return this._FULIAOKA;
			}
			set
			{
				if ((this._FULIAOKA != value))
				{
					this.OnFULIAOKAChanging(value);
					this.SendPropertyChanging();
					this._FULIAOKA = value;
					this.SendPropertyChanged("FULIAOKA");
					this.OnFULIAOKAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULIAOKA_INFO", DbType="NVarChar(500)")]
		public string FULIAOKA_INFO
		{
			get
			{
				return this._FULIAOKA_INFO;
			}
			set
			{
				if ((this._FULIAOKA_INFO != value))
				{
					this.OnFULIAOKA_INFOChanging(value);
					this.SendPropertyChanging();
					this._FULIAOKA_INFO = value;
					this.SendPropertyChanged("FULIAOKA_INFO");
					this.OnFULIAOKA_INFOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OperClothLog")]
	public partial class OperClothLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _c_class;
		
		private int _SYTLE_NO;
		
		private int _BIG_NO;
		
		private System.Nullable<int> _COUNT;
		
		private string _DATE;
		
		private string _OPER;
		
		private string _USER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_classChanging(string value);
    partial void Onc_classChanged();
    partial void OnSYTLE_NOChanging(int value);
    partial void OnSYTLE_NOChanged();
    partial void OnBIG_NOChanging(int value);
    partial void OnBIG_NOChanged();
    partial void OnCOUNTChanging(System.Nullable<int> value);
    partial void OnCOUNTChanged();
    partial void OnDATEChanging(string value);
    partial void OnDATEChanged();
    partial void OnOPERChanging(string value);
    partial void OnOPERChanged();
    partial void OnUSERChanging(string value);
    partial void OnUSERChanged();
    #endregion
		
		public OperClothLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_class", DbType="NVarChar(50)")]
		public string c_class
		{
			get
			{
				return this._c_class;
			}
			set
			{
				if ((this._c_class != value))
				{
					this.Onc_classChanging(value);
					this.SendPropertyChanging();
					this._c_class = value;
					this.SendPropertyChanged("c_class");
					this.Onc_classChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYTLE_NO", DbType="Int NOT NULL")]
		public int SYTLE_NO
		{
			get
			{
				return this._SYTLE_NO;
			}
			set
			{
				if ((this._SYTLE_NO != value))
				{
					this.OnSYTLE_NOChanging(value);
					this.SendPropertyChanging();
					this._SYTLE_NO = value;
					this.SendPropertyChanged("SYTLE_NO");
					this.OnSYTLE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIG_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BIG_NO
		{
			get
			{
				return this._BIG_NO;
			}
			set
			{
				if ((this._BIG_NO != value))
				{
					this.OnBIG_NOChanging(value);
					this.SendPropertyChanging();
					this._BIG_NO = value;
					this.SendPropertyChanged("BIG_NO");
					this.OnBIG_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this.OnCOUNTChanging(value);
					this.SendPropertyChanging();
					this._COUNT = value;
					this.SendPropertyChanged("COUNT");
					this.OnCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="NVarChar(50)")]
		public string DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPER", DbType="NVarChar(50)")]
		public string OPER
		{
			get
			{
				return this._OPER;
			}
			set
			{
				if ((this._OPER != value))
				{
					this.OnOPERChanging(value);
					this.SendPropertyChanging();
					this._OPER = value;
					this.SendPropertyChanged("OPER");
					this.OnOPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[USER]", Storage="_USER", DbType="NVarChar(50)")]
		public string USER
		{
			get
			{
				return this._USER;
			}
			set
			{
				if ((this._USER != value))
				{
					this.OnUSERChanging(value);
					this.SendPropertyChanging();
					this._USER = value;
					this.SendPropertyChanged("USER");
					this.OnUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UpCloth")]
	public partial class UpCloth : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SYTLE_NO;
		
		private int _BIG_NO;
		
		private string _STYLE;
		
		private string _C_CLASS;
		
		private string _KUOXING;
		
		private string _KUANSONGFENGGE;
		
		private string _YISHENPIANSHU;
		
		private string _YISHENZAOXING;
		
		private string _LINGXING;
		
		private string _XIUXING;
		
		private string _PIANSHU;
		
		private string _CHANGDUAN;
		
		private string _YIXIUZAOXING;
		
		private string _COMMENTS;
		
		private string _YANGYI_LOCATION;
		
		private string _YANGYI_INFO;
		
		private string _KUANSHI_LOCATION;
		
		private string _KUANSHI_INFO;
		
		private string _BANXING_LOCAITON;
		
		private string _BANXING_INFO;
		
		private string _GONGYIWENJIAN;
		
		private string _GONGYIWENJIAN_INFO;
		
		private string _FULIAOKA;
		
		private string _FULIAOKA_INFO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSYTLE_NOChanging(int value);
    partial void OnSYTLE_NOChanged();
    partial void OnBIG_NOChanging(int value);
    partial void OnBIG_NOChanged();
    partial void OnSTYLEChanging(string value);
    partial void OnSTYLEChanged();
    partial void OnC_CLASSChanging(string value);
    partial void OnC_CLASSChanged();
    partial void OnKUOXINGChanging(string value);
    partial void OnKUOXINGChanged();
    partial void OnKUANSONGFENGGEChanging(string value);
    partial void OnKUANSONGFENGGEChanged();
    partial void OnYISHENPIANSHUChanging(string value);
    partial void OnYISHENPIANSHUChanged();
    partial void OnYISHENZAOXINGChanging(string value);
    partial void OnYISHENZAOXINGChanged();
    partial void OnLINGXINGChanging(string value);
    partial void OnLINGXINGChanged();
    partial void OnXIUXINGChanging(string value);
    partial void OnXIUXINGChanged();
    partial void OnPIANSHUChanging(string value);
    partial void OnPIANSHUChanged();
    partial void OnCHANGDUANChanging(string value);
    partial void OnCHANGDUANChanged();
    partial void OnYIXIUZAOXINGChanging(string value);
    partial void OnYIXIUZAOXINGChanged();
    partial void OnCOMMENTSChanging(string value);
    partial void OnCOMMENTSChanged();
    partial void OnYANGYI_LOCATIONChanging(string value);
    partial void OnYANGYI_LOCATIONChanged();
    partial void OnYANGYI_INFOChanging(string value);
    partial void OnYANGYI_INFOChanged();
    partial void OnKUANSHI_LOCATIONChanging(string value);
    partial void OnKUANSHI_LOCATIONChanged();
    partial void OnKUANSHI_INFOChanging(string value);
    partial void OnKUANSHI_INFOChanged();
    partial void OnBANXING_LOCAITONChanging(string value);
    partial void OnBANXING_LOCAITONChanged();
    partial void OnBANXING_INFOChanging(string value);
    partial void OnBANXING_INFOChanged();
    partial void OnGONGYIWENJIANChanging(string value);
    partial void OnGONGYIWENJIANChanged();
    partial void OnGONGYIWENJIAN_INFOChanging(string value);
    partial void OnGONGYIWENJIAN_INFOChanged();
    partial void OnFULIAOKAChanging(string value);
    partial void OnFULIAOKAChanged();
    partial void OnFULIAOKA_INFOChanging(string value);
    partial void OnFULIAOKA_INFOChanged();
    #endregion
		
		public UpCloth()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYTLE_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYTLE_NO
		{
			get
			{
				return this._SYTLE_NO;
			}
			set
			{
				if ((this._SYTLE_NO != value))
				{
					this.OnSYTLE_NOChanging(value);
					this.SendPropertyChanging();
					this._SYTLE_NO = value;
					this.SendPropertyChanged("SYTLE_NO");
					this.OnSYTLE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIG_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BIG_NO
		{
			get
			{
				return this._BIG_NO;
			}
			set
			{
				if ((this._BIG_NO != value))
				{
					this.OnBIG_NOChanging(value);
					this.SendPropertyChanging();
					this._BIG_NO = value;
					this.SendPropertyChanged("BIG_NO");
					this.OnBIG_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STYLE", DbType="NVarChar(50)")]
		public string STYLE
		{
			get
			{
				return this._STYLE;
			}
			set
			{
				if ((this._STYLE != value))
				{
					this.OnSTYLEChanging(value);
					this.SendPropertyChanging();
					this._STYLE = value;
					this.SendPropertyChanged("STYLE");
					this.OnSTYLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CLASS", DbType="NVarChar(50)")]
		public string C_CLASS
		{
			get
			{
				return this._C_CLASS;
			}
			set
			{
				if ((this._C_CLASS != value))
				{
					this.OnC_CLASSChanging(value);
					this.SendPropertyChanging();
					this._C_CLASS = value;
					this.SendPropertyChanged("C_CLASS");
					this.OnC_CLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUOXING", DbType="NVarChar(50)")]
		public string KUOXING
		{
			get
			{
				return this._KUOXING;
			}
			set
			{
				if ((this._KUOXING != value))
				{
					this.OnKUOXINGChanging(value);
					this.SendPropertyChanging();
					this._KUOXING = value;
					this.SendPropertyChanged("KUOXING");
					this.OnKUOXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUANSONGFENGGE", DbType="NVarChar(50)")]
		public string KUANSONGFENGGE
		{
			get
			{
				return this._KUANSONGFENGGE;
			}
			set
			{
				if ((this._KUANSONGFENGGE != value))
				{
					this.OnKUANSONGFENGGEChanging(value);
					this.SendPropertyChanging();
					this._KUANSONGFENGGE = value;
					this.SendPropertyChanged("KUANSONGFENGGE");
					this.OnKUANSONGFENGGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YISHENPIANSHU", DbType="NVarChar(50)")]
		public string YISHENPIANSHU
		{
			get
			{
				return this._YISHENPIANSHU;
			}
			set
			{
				if ((this._YISHENPIANSHU != value))
				{
					this.OnYISHENPIANSHUChanging(value);
					this.SendPropertyChanging();
					this._YISHENPIANSHU = value;
					this.SendPropertyChanged("YISHENPIANSHU");
					this.OnYISHENPIANSHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YISHENZAOXING", DbType="NVarChar(50)")]
		public string YISHENZAOXING
		{
			get
			{
				return this._YISHENZAOXING;
			}
			set
			{
				if ((this._YISHENZAOXING != value))
				{
					this.OnYISHENZAOXINGChanging(value);
					this.SendPropertyChanging();
					this._YISHENZAOXING = value;
					this.SendPropertyChanged("YISHENZAOXING");
					this.OnYISHENZAOXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINGXING", DbType="NVarChar(50)")]
		public string LINGXING
		{
			get
			{
				return this._LINGXING;
			}
			set
			{
				if ((this._LINGXING != value))
				{
					this.OnLINGXINGChanging(value);
					this.SendPropertyChanging();
					this._LINGXING = value;
					this.SendPropertyChanged("LINGXING");
					this.OnLINGXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XIUXING", DbType="NVarChar(50)")]
		public string XIUXING
		{
			get
			{
				return this._XIUXING;
			}
			set
			{
				if ((this._XIUXING != value))
				{
					this.OnXIUXINGChanging(value);
					this.SendPropertyChanging();
					this._XIUXING = value;
					this.SendPropertyChanged("XIUXING");
					this.OnXIUXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIANSHU", DbType="NVarChar(50)")]
		public string PIANSHU
		{
			get
			{
				return this._PIANSHU;
			}
			set
			{
				if ((this._PIANSHU != value))
				{
					this.OnPIANSHUChanging(value);
					this.SendPropertyChanging();
					this._PIANSHU = value;
					this.SendPropertyChanged("PIANSHU");
					this.OnPIANSHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGDUAN", DbType="NVarChar(50)")]
		public string CHANGDUAN
		{
			get
			{
				return this._CHANGDUAN;
			}
			set
			{
				if ((this._CHANGDUAN != value))
				{
					this.OnCHANGDUANChanging(value);
					this.SendPropertyChanging();
					this._CHANGDUAN = value;
					this.SendPropertyChanged("CHANGDUAN");
					this.OnCHANGDUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YIXIUZAOXING", DbType="NVarChar(50)")]
		public string YIXIUZAOXING
		{
			get
			{
				return this._YIXIUZAOXING;
			}
			set
			{
				if ((this._YIXIUZAOXING != value))
				{
					this.OnYIXIUZAOXINGChanging(value);
					this.SendPropertyChanging();
					this._YIXIUZAOXING = value;
					this.SendPropertyChanged("YIXIUZAOXING");
					this.OnYIXIUZAOXINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="NVarChar(50)")]
		public string COMMENTS
		{
			get
			{
				return this._COMMENTS;
			}
			set
			{
				if ((this._COMMENTS != value))
				{
					this.OnCOMMENTSChanging(value);
					this.SendPropertyChanging();
					this._COMMENTS = value;
					this.SendPropertyChanged("COMMENTS");
					this.OnCOMMENTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YANGYI_LOCATION", DbType="NVarChar(100)")]
		public string YANGYI_LOCATION
		{
			get
			{
				return this._YANGYI_LOCATION;
			}
			set
			{
				if ((this._YANGYI_LOCATION != value))
				{
					this.OnYANGYI_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._YANGYI_LOCATION = value;
					this.SendPropertyChanged("YANGYI_LOCATION");
					this.OnYANGYI_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YANGYI_INFO", DbType="NVarChar(100)")]
		public string YANGYI_INFO
		{
			get
			{
				return this._YANGYI_INFO;
			}
			set
			{
				if ((this._YANGYI_INFO != value))
				{
					this.OnYANGYI_INFOChanging(value);
					this.SendPropertyChanging();
					this._YANGYI_INFO = value;
					this.SendPropertyChanged("YANGYI_INFO");
					this.OnYANGYI_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUANSHI_LOCATION", DbType="NVarChar(100)")]
		public string KUANSHI_LOCATION
		{
			get
			{
				return this._KUANSHI_LOCATION;
			}
			set
			{
				if ((this._KUANSHI_LOCATION != value))
				{
					this.OnKUANSHI_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._KUANSHI_LOCATION = value;
					this.SendPropertyChanged("KUANSHI_LOCATION");
					this.OnKUANSHI_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUANSHI_INFO", DbType="NVarChar(100)")]
		public string KUANSHI_INFO
		{
			get
			{
				return this._KUANSHI_INFO;
			}
			set
			{
				if ((this._KUANSHI_INFO != value))
				{
					this.OnKUANSHI_INFOChanging(value);
					this.SendPropertyChanging();
					this._KUANSHI_INFO = value;
					this.SendPropertyChanged("KUANSHI_INFO");
					this.OnKUANSHI_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANXING_LOCAITON", DbType="NVarChar(100)")]
		public string BANXING_LOCAITON
		{
			get
			{
				return this._BANXING_LOCAITON;
			}
			set
			{
				if ((this._BANXING_LOCAITON != value))
				{
					this.OnBANXING_LOCAITONChanging(value);
					this.SendPropertyChanging();
					this._BANXING_LOCAITON = value;
					this.SendPropertyChanged("BANXING_LOCAITON");
					this.OnBANXING_LOCAITONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANXING_INFO", DbType="NVarChar(100)")]
		public string BANXING_INFO
		{
			get
			{
				return this._BANXING_INFO;
			}
			set
			{
				if ((this._BANXING_INFO != value))
				{
					this.OnBANXING_INFOChanging(value);
					this.SendPropertyChanging();
					this._BANXING_INFO = value;
					this.SendPropertyChanged("BANXING_INFO");
					this.OnBANXING_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGYIWENJIAN", DbType="NVarChar(100)")]
		public string GONGYIWENJIAN
		{
			get
			{
				return this._GONGYIWENJIAN;
			}
			set
			{
				if ((this._GONGYIWENJIAN != value))
				{
					this.OnGONGYIWENJIANChanging(value);
					this.SendPropertyChanging();
					this._GONGYIWENJIAN = value;
					this.SendPropertyChanged("GONGYIWENJIAN");
					this.OnGONGYIWENJIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGYIWENJIAN_INFO", DbType="NVarChar(500)")]
		public string GONGYIWENJIAN_INFO
		{
			get
			{
				return this._GONGYIWENJIAN_INFO;
			}
			set
			{
				if ((this._GONGYIWENJIAN_INFO != value))
				{
					this.OnGONGYIWENJIAN_INFOChanging(value);
					this.SendPropertyChanging();
					this._GONGYIWENJIAN_INFO = value;
					this.SendPropertyChanged("GONGYIWENJIAN_INFO");
					this.OnGONGYIWENJIAN_INFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULIAOKA", DbType="NVarChar(100)")]
		public string FULIAOKA
		{
			get
			{
				return this._FULIAOKA;
			}
			set
			{
				if ((this._FULIAOKA != value))
				{
					this.OnFULIAOKAChanging(value);
					this.SendPropertyChanging();
					this._FULIAOKA = value;
					this.SendPropertyChanged("FULIAOKA");
					this.OnFULIAOKAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULIAOKA_INFO", DbType="NVarChar(500)")]
		public string FULIAOKA_INFO
		{
			get
			{
				return this._FULIAOKA_INFO;
			}
			set
			{
				if ((this._FULIAOKA_INFO != value))
				{
					this.OnFULIAOKA_INFOChanging(value);
					this.SendPropertyChanging();
					this._FULIAOKA_INFO = value;
					this.SendPropertyChanged("FULIAOKA_INFO");
					this.OnFULIAOKA_INFOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
