// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_clothparttype_children1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_clothparttype_children1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305141544392_add_clothparttype_children1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
