// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class change_Clothes_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_Clothes_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "201305120626012_change_Clothes_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
