// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_clothparttype_children : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_clothparttype_children));
        
        string IMigrationMetadata.Id
        {
            get { return "201305141537273_add_clothparttype_children"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
