// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_class_session_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_class_session_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201305061539297_Add_class_session_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
